### ISSUE TITLE
Integrity checksum for stylesheet is outdated

### ISSUE THREAD

**Issue by ThomasKoppensteiner** [epidrome/cover-card#27]
The `integrity` checksum for the "fontawesome" stylesheet is outdated.

**Comment by epidrome** [comment]
thank you for raising this issue and making a PR #28 

could you please update your post or provide some link-documentation about the correct reference to Font Awesome?

please note that there is also a related open issue #25 that regards the multiple available options for importing those external icons to the theme

**Comment by epidrome** [comment]
The theme has been updated to use [fontawesome kits](https://fontawesome.com/kits) which was recently introduced and supports automatic upgrade to the latest version of `fontawesome`

In practice, starting with this version users can use any new icon that shows up and we do not need to care anymore about changing version numbers.
